-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 10:17:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(44) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `idtweet` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idtweet`),
  INDEX `fk_tweet_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_tweet_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `idorganisation` INT NOT NULL,
  `name` VARCHAR(44) NOT NULL,
  `website_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorganisation`));


-- -----------------------------------------------------
-- Table `mydb`.`user_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_organization` (
  `user_iduser` INT NOT NULL,
  `organization_idorganisation` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `organization_idorganisation`),
  INDEX `fk_user_has_organization_organization1_idx` (`organization_idorganisation` ASC),
  INDEX `fk_user_has_organization_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_organization_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_organization_organization1`
    FOREIGN KEY (`organization_idorganisation`)
    REFERENCES `mydb`.`organization` (`idorganisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
